### ISSUE TITLE
openml.datasets.dataset.get_data ... 503 status code

### ISSUE THREAD

**Issue by algormx** [ITMO-NSS-team/MetaFEDOT#36]
Предлагается добавить опцию читать из кэша и конструировать нужные объекты избегая запрос ко внешнему сервису.

**Comment by MorrisNein** [comment]
@algormx опишите полностью проблему и способ воспроизведения. Обращения к серверам при уже загруженном датасете быть не должно.

**Comment by MorrisNein** [comment]
Столкнулся с ошибкой из заголовка. Она говорит не об ошибке кэширования, а о том, что датасет не загружен в кэш. Это внешняя проблема. Мы ведь не можем избавиться от зависимостей полностью.

Объясните, что вы предлагаете: хранить все используемые данные у себя и распространять с фреймворком?
